name: CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - uses: actions/checkout@v2
      
    - name: Use Java8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build debug apk
      run: ./gradlew clean assembleDebug

    - name: Create release and upload apk
      # https://github.com/marketplace/actions/create-release-with-debug-apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v3.0
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: termux-sdl-debug-${{steps.tag_name}}.apk
        asset_content_type: application/zip